### ISSUE TITLE
Dim mode hides top button dropdown menus

### ISSUE THREAD

**Issue by sex-defender** [f3rked/maej3rked-tools#16]
with dim mode on, the dropdown menu buttons on the top of the site (info, watch, play, etc.) get hidden behind whatever cam you're watching.

pics of what i'm talking about
![image](https://github.com/user-attachments/assets/f46cf07d-583a-45cc-a52f-acc11418e297)
![image](https://github.com/user-attachments/assets/688addb5-5193-4316-b35c-e59cda2e485d)

current settings
![image](https://github.com/user-attachments/assets/48d4c88a-a886-4673-836e-7aef7bea77cc)
no chat settings, no new keybinds, etc.

issue persists with adblocks n other things that might potentially interfere.

**Comment by f3rked** [comment]
yea dim mode is kinda fucked - i mostly ignored it/forgot about it since the site is darker now than when that was added.  i'll take a look at it and see how annoying it is to update the styles, but i might remove it if it seems like a lot of work.

**Comment by f3rked** [comment]
closed by https://github.com/f3rked/maej3rked-tools/pull/27 thanks to @tootster
