### ISSUE TITLE
Violentmonkey vs Tampermonkey

### ISSUE THREAD

**Issue by monokrome** [f3rked/maej3rked-tools#23]
Is there a reason Tampermonkey is recommended over Violentmonkey? Tampermonkey is spyware. Violent may be the better recommendation unless there are features missing, but I don't think there are.

**Comment by f3rked** [comment]
updated [readme](https://github.com/f3rked/maej3rked-tools/commit/a98d55a1148d02c6c07de66b7388e451b2717859)
